---
title: "Cargar datos FIFA y visualziar con plot()"
author: "Rubén Pizarro Gurrola"
date: "12/3/2022"
output: html_document
---

# Cargar librerías
```{r message=FALSE, warning=FALSE}
library(readr)
library(dplyr)
library(fdth)
```

# Cargar los datos

```{r}
url <- "https://raw.githubusercontent.com/rpizarrog/Machine-Learning-con-R/main/datos/datos.limpios.csv"
fifa <- read.csv(url)
```


# Mostrar los primeros 10 registros

Variables de interés

* Age
* Estatura
* PesoKgs
* Nationality

```{r}
head(fifa[,c('Name', "Age", "Nationality", "Estatura", "PesoKgs")], 10)
```

# filtro de MExico


```{r}
# mexico <- filter(fifa, Nationality == "Mexico")
# mexico
```

# Visualiza con plot()


## Dispersión de Estatura y PesoKgs

```{r}
plot(x = fifa$Estatura, y = fifa$PesoKgs, col='blue')
```
# Gráfica de barra de nacionalidad de jugadores

```{r}
tabla_nac <- fdt_cat(fifa$Nationality)
tabla_nac
```

```{r}
top.ten <- head(tabla_nac, 10)

barplot(height = top.ten$f, 
        names.arg = top.ten$Category)
```


# Agrupar datos de edades
```{r}
tabla.edades <- fdt(fifa$Age, 
                    start = min(fifa$Age), 
                    end = max(fifa$Age), 
                    h = 5)
tabla.edades
```

# graficar con un histograma
```{r}
hist(fifa$Age)
```

